#!/usr/bin/env python3
"""Generate a reserved-memory .dtsi body from the vendor FDT.

Every fixed (reg-based) reservation in the vendor device tree is carried over
verbatim.  Getting this wrong is fatal: these regions hold live firmware
(BL31, TEE, GenieZone, SSPM, MCUPM, SCP, ADSP, modem), and a mainline kernel
that allocates from them corrupts the secure world instead of booting.
"""
import os
import subprocess
import sys

# Self-locating: script lives at the kernel tree root next to the vendor FDT
# extract and the dts it regenerates.
HERE = os.path.dirname(os.path.abspath(__file__))
FDT = os.path.join(HERE, "fdt")
OUT = os.path.join(HERE, "arch/arm64/boot/dts/mediatek/",
                   "mt6991-realme-rmx6688-resmem.dtsi")

# The bootloader framebuffer must leave the linear map so that simplefb can
# ioremap_wc() it without conflicting memory attributes.
FORCE_NOMAP = {"mblock-16-framebuffer"}

# Described by hand in the board DTS instead, as a mainline "ramoops" node so
# that pstore claims the region the vendor kernel also uses for its console
# log.  Emitting it here as well would reserve the range twice.
SKIP = {"mblock-2-pstore"}


def fdtget(args):
    r = subprocess.run(["fdtget"] + args, capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else None


def main():
    listing = fdtget(["-l", FDT, "/reserved-memory"])
    if not listing:
        sys.exit("cannot read /reserved-memory from " + FDT)

    body, skipped, kept = [], [], 0
    for child in listing.split():
        node = "/reserved-memory/" + child

        if child in SKIP:
            skipped.append("%s (described by hand in the board DTS)" % child)
            continue

        props = (fdtget(["-p", FDT, node]) or "").split()

        if "reg" not in props:
            skipped.append("%s (no reg: dynamic/size-based)" % child)
            continue
        words = (fdtget(["-t", "x", FDT, node, "reg"]) or "").split()
        if len(words) != 4:
            skipped.append("%s (reg has %d cells, expected 4)" % (child, len(words)))
            continue

        hi, lo, shi, slo = (int(w, 16) for w in words)
        addr, size = (hi << 32) | lo, (shi << 32) | slo
        if size == 0:
            skipped.append("%s (zero size)" % child)
            continue

        compat = fdtget(["-t", "s", FDT, node, "compatible"]) if "compatible" in props else None
        nomap = "no-map" in props or child in FORCE_NOMAP

        body.append("\t%s@%x {" % (child, addr))
        if compat:
            joined = '", "'.join(compat.split("\n"))
            body.append('\t\tcompatible = "%s";' % joined)
        body.append("\t\treg = <0x%x 0x%08x 0x%x 0x%08x>;" % (hi, lo, shi, slo))
        if nomap:
            body.append("\t\tno-map;")
        if "reusable" in props:
            body.append("\t\treusable;")
        body.append("\t};")
        body.append("")
        kept += 1

    header = [
        "// SPDX-License-Identifier: (GPL-2.0 OR MIT)",
        "/*",
        " * Fixed memory reservations for realme GT7 (RMX6688), MT6991.",
        " *",
        " * GENERATED by gen_resmem.py from the vendor /sys/firmware/fdt -- do not",
        " * edit by hand.  Included from inside the reserved-memory node.",
        " */",
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(header + body) + "\n")

    print("wrote %s" % OUT)
    print("carried over %d fixed reservations" % kept)
    print("skipped %d:" % len(skipped))
    for s in skipped:
        print("  - %s" % s)


if __name__ == "__main__":
    main()
